[package]
name = "git-dumper"
version = "0.1.0"
edition = "2021"
description = "A tool to dump exposed .git directories"

[dependencies]
anyhow = "1.0.65"
clap = { version = "3.2", features = ["cargo"] }
lazy_static = "1.4.0"
miniz_oxide = "0.6.2"
regex = "1.6"
reqwest = "0.11"
tokio = { version = "1.21", features = ["net", "sync", "rt", "rt-multi-thread", "macros"] }
